name: Dragons API Continuous Integration

on:
  push:
    branches: [ main ]  # Only run on push events to the main branch
  pull_request:
    branches: [ main ]  # Only run on pull requests targeting the main branch

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install requests
          pip install pytest
          pip install boto3  # Add boto3 to the list of dependencies
          pip install pytest-mock  # Ensure pytest-mock is installed
      - name: Run Python tests
        env:
          DRAGON_API_TOKEN: ${{ secrets.DRAGON_API_TOKEN }}  # Set the environment variable for use in tests
        run: python3 -m pytest tests/

  postman-tests:
    needs: python-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "tests/Dragons AWS - Lambda.postman_collection.json"
